# Generated by Django 5.1.4 on 2024-12-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='category',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='sub_category',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
